### ISSUE TITLE
Parser bug: minus & superscript

### ISSUE THREAD

**Issue by charleskawczynski** [domluna/JuliaFormatter.jl#743] opened 2023-07-12 18:13 UTC
MWE:

```julia
using JuliaFormatter
format_text("foo(ᶜa) = - ᶜa") # errors
format_text("foo(ᶜa) = -ᶜa") # errors
format_text("foo(ᶜa) = -(ᶜa)") # passes
```

**Comment by domluna** [comment] 2023-08-13 02:48
I have a fix for this bug is there a list somewhere of all these types of characters with are added at the start?

The problem is the formatter will squish these together which is fine in 99.9% of cases but here it produces a parsing ambiguity it seems

```
julia> Meta.parse("foo(ᶜa) = -ᶜa")
ERROR: ParseError:
# Error @ none:1:11
foo(ᶜa) = -ᶜa
#         └┘ ── not a unary operator
Stacktrace:
 [1] #parse#3
   @ Base.Meta ./meta.jl:244 [inlined]
 [2] parse
   @ Base.Meta ./meta.jl:236 [inlined]
 [3] parse(str::String; filename::String, raise::Bool, depwarn::Bool)
   @ Base.Meta ./meta.jl:278
 [4] parse(str::String)
   @ Base.Meta ./meta.jl:276
 [5] top-level scope
   @ REPL[61]:1
```

**Closed** 2023-08-13 03:32 UTC
